import { manifest } from '../../../shared/manifest';

export const colorEstuaryManifest = manifest({
  id: "color-estuary",
  title: "Color Estuary",
  category: "Ambient",
  description: "A broad branching channel wanders between calm fields of mint, sand, and muted blue.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.18, max: 0.4 },
    },
    { name: "channelWidth", type: "float", default: 0.12, min: 0.04, max: 0.28, step: 0.01,
      label: "Channel width",
      description: "Width of the branching ribbon between the colored regions.",
      group: "Shape",
      random: { min: 0.08, max: 0.17 },
    },
    { name: "curvature", type: "float", default: 0.65, min: 0, max: 1.2, step: 0.01,
      label: "Curvature",
      description: "Amount of bending along the channel branches.",
      group: "Shape",
      random: { min: 0.4, max: 0.85 },
    },
    { name: "angle", type: "float", default: 20, min: -90, max: 90, step: 0.01,
      label: "Angle",
      description: "Orientation of the branching composition in degrees.",
      group: "Shape",
      random: { min: -30, max: 50 },
    },
    { name: "drift", type: "float", default: 0.75, min: 0, max: 1.4, step: 0.01,
      label: "Tide",
      description: "Distance the junction wanders and the branches breathe.",
      group: "Motion",
      random: { min: 0.4, max: 1 },
    },
    { name: "color1", type: "color", default: "#afc7b8",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#dfcdaa",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#8cabb5",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#356575",
      label: "Background",
      description: "Base color behind the shapes and between their edges.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: { min: 0.7, max: 1.1 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      random: { min: 0.7, max: 1.15 },
      advanced: true,
    },
  ],
});
