import { manifest } from '../../../shared/manifest';

export const duneSilkManifest = manifest({
  id: "dune-silk",
  title: "Dune Silk",
  category: 'Ambient',
  description: "Warm amber ribbons of light flow across a deep midnight blue.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.1, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.04, max: 0.26 },
    },
    { name: "scale", type: "float", default: 1, min: 0.5, max: 2, step: 0.01,
      label: "Scale",
      description: "Size of the flowing band pattern.",
      group: "Shape",
      random: { min: 0.7, max: 1.3 },
    },
    { name: "distortion", type: "float", default: 0.65, min: 0, max: 1.5, step: 0.01,
      label: "Distortion",
      description: "Strength of the slow organic warp that bends the bands.",
      group: "Motion",
      random: { min: 0.35, max: 0.9 },
    },
    { name: "softness", type: "float", default: 0.55, min: 0, max: 1, step: 0.01,
      label: "Softness",
      description: "How diffuse and wide the flowing bands appear.",
      group: "Shape",
      random: { min: 0.35, max: 0.75 },
    },
    { name: "glow", type: "float", default: 0.8, min: 0, max: 2, step: 0.01,
      label: "Glow",
      description: "Luminous halo along the brightest band edges.",
      group: "Color",
      random: { min: 0.5, max: 1.1 },
    },
    { name: "brightness", type: "float", default: 1.15, min: 0.2, max: 2, step: 0.01,
      label: "Brightness",
      description: "Light intensity of this shader.",
      group: "Color",
      random: { min: 0.8, max: 1.5 },
    },
    { name: "color1", type: "color", default: "#06121c",
      label: "Deep shadow",
      description: "Deepest background tone behind the bands.",
      group: "Color",
      colorRole: "surface",
      random: false,
    },
    { name: "color2", type: "color", default: "#1a545e",
      label: "Midtone",
      description: "Teal body of the flowing bands.",
      group: "Color",
      colorRole: "primary",
    },
    { name: "color3", type: "color", default: "#ffb063",
      label: "Highlight",
      description: "Warm amber crest on the brightest band edges.",
      group: "Color",
      colorRole: "secondary",
    },
    { name: "saturation", type: "float", default: 0.9, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
  ],
});
