import { manifest } from '../../../shared/manifest';

export const gradientDriftManifest = manifest({
  id: "gradient-drift",
  title: "Gradient Drift",
  description: "Wide, silky bands of color that slowly turn and drift.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "scale", type: "float", default: 1, min: 0.3, max: 3, step: 0.01,
      label: "Scale",
      description: "Spatial frequency of the pattern.",
      group: "Shape",
      random: { min: 0.46, max: 1.54 },
    },
    { name: "warp", type: "float", default: 0.35, min: 0, max: 1, step: 0.01,
      label: "Warp",
      description: "Strength of the flowing distortion.",
      group: "Shape",
      random: { min: 0.15, max: 0.55 },
    },
    { name: "shadow", type: "color", default: "#29216b",
      label: "Shadow",
      description: "Choose the shadow of the palette.",
      group: "Color",
    },
    { name: "midtone", type: "color", default: "#e779aa",
      label: "Midtone",
      description: "Choose the midtone of the palette.",
      group: "Color",
    },
    { name: "highlight", type: "color", default: "#ffd6a0",
      label: "Highlight",
      description: "Choose the highlight of the palette.",
      group: "Color",
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: { min: 0.6, max: 1.2 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "angle", type: "float", default: 0, min: -180, max: 180, step: 1,
      label: "Starting angle",
      description: "Rotate the initial orientation of the color bands.",
      group: "Motion",
      advanced: true,
      unit: "°",
      random: { min: -72, max: 72 },
    },
    { name: "rotationRate", type: "float", default: 1, min: -2, max: 2, step: 0.01,
      label: "Rotation rate",
      description: "Relative rotation speed; zero holds the angle.",
      group: "Motion",
      advanced: true,
      random: { min: 0.2, max: 1.8 },
    },
    { name: "driftRate", type: "float", default: 1, min: -2, max: 2, step: 0.01,
      label: "Drift rate",
      description: "Relative speed and direction of the traveling bands.",
      group: "Motion",
      advanced: true,
      random: { min: 0.2, max: 1.8 },
    },
    { name: "warpFrequency", type: "float", default: 1, min: 0.2, max: 3, step: 0.01,
      label: "Warp frequency",
      description: "Number of bends across the gradient.",
      group: "Shape",
      advanced: true,
      random: { min: 0.44, max: 1.56 },
    },
    { name: "midtonePosition", type: "float", default: 0.55, min: 0.15, max: 0.85, step: 0.01,
      label: "Midtone position",
      description: "Where the middle color meets the highlight.",
      group: "Color",
      advanced: true,
      random: { min: 0.41, max: 0.69 },
    },
  ],
});
