import { manifest } from '../../../shared/manifest';

export const contourDunesManifest = manifest({
  id: "contour-dunes",
  title: "Contour Dunes",
  category: 'Landscapes',
  description: "Copper and indigo contour lines flow like wind-shaped dunes.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.2, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "scale", type: "float", default: 1, min: 0.4, max: 3, step: 0.01,
      label: "Scale",
      description: "Spatial frequency of the pattern.",
      group: "Shape",
      random: { min: 0.48, max: 1.52 },
    },
    { name: "lines", type: "float", default: 10, min: 4, max: 20, step: 0.01,
      label: "Contours",
      description: "Number of contour levels.",
      group: "Shape",
      random: { min: 6.8, max: 13.2 },
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Light intensity of this shader.",
      group: "Color",
      random: { min: 0.6, max: 1.2 },
    },
    { name: "color1", type: "color", default: "#192744",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#d6a06b",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "lineThickness", type: "float", default: 0.025, min: 0.005, max: 0.15, step: 0.005,
      label: "Line thickness",
      description: "Width of each contour line.",
      group: "Shape",
      advanced: true,
      random: { min: 0.005, max: 0.054 },
    },
    { name: "edgeSoftness", type: "float", default: 0.025, min: 0.005, max: 0.15, step: 0.005,
      label: "Edge softness",
      description: "Softness at the contour edges.",
      group: "Shape",
      advanced: true,
      random: { min: 0.005, max: 0.054 },
    },
    { name: "distortion", type: "float", default: 0.55, min: 0, max: 1.5, step: 0.01,
      label: "Terrain distortion",
      description: "Amount of bending in the terrain.",
      group: "Shape",
      advanced: true,
      random: { min: 0.25, max: 0.85 },
    },
    { name: "fineDetail", type: "float", default: 0.08, min: 0, max: 0.2, step: 0.005,
      label: "Fine detail",
      description: "Strength of smaller terrain features.",
      group: "Shape",
      advanced: true,
      random: { min: 0.04, max: 0.12 },
    },
    { name: "angle", type: "float", default: 0, min: -180, max: 180, step: 1,
      label: "Angle",
      description: "Rotate the terrain.",
      group: "Motion",
      advanced: true,
      unit: "°",
      random: { min: -72, max: 72 },
    },
    { name: "contourIntensity", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Contour intensity",
      description: "Brightness of the contour lines.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.4 },
    },
  ],
});
