import { manifest } from '../../../shared/manifest';

export const silkRibbonsManifest = manifest({
  id: "silk-ribbons",
  title: "Silk Ribbons",
  category: 'Ambient',
  description: "Pearlescent bands of rose and blue silk unfurl in the dark.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.25, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "width", type: "float", default: 0.55, min: 0.1, max: 1, step: 0.01,
      label: "Width",
      description: "Width of each ribbon.",
      group: "Shape",
      random: { min: 0.37, max: 0.73 },
    },
    { name: "sway", type: "float", default: 0.6, min: 0, max: 1, step: 0.01,
      label: "Sway",
      description: "Amount of ribbon movement.",
      group: "Motion",
      random: { min: 0.4, max: 0.8 },
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Light intensity of this shader.",
      group: "Color",
      random: { min: 0.6, max: 1.2 },
    },
    { name: "color1", type: "color", default: "#ea91b7",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#779de8",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "ribbonCount", type: "int", default: 5, min: 1, max: 8, step: 1,
      label: "Ribbon count",
      description: "Number of overlapping silk ribbons.",
      group: "Shape",
      advanced: true,
      random: { min: 3.6, max: 6.4 },
    },
    { name: "spacing", type: "float", default: 0.105, min: 0.03, max: 0.2, step: 0.005,
      label: "Spacing",
      description: "Distance between neighboring ribbons.",
      group: "Shape",
      advanced: true,
      random: { min: 0.071, max: 0.139 },
    },
    { name: "angle", type: "float", default: 0, min: -180, max: 180, step: 1,
      label: "Angle",
      description: "Rotate the ribbon arrangement.",
      group: "Motion",
      advanced: true,
      unit: "°",
      random: { min: -72, max: 72 },
    },
    { name: "waveFrequency", type: "float", default: 1, min: 0.2, max: 3, step: 0.01,
      label: "Wave frequency",
      description: "Number of curves along each ribbon.",
      group: "Shape",
      advanced: true,
      random: { min: 0.44, max: 1.56 },
    },
    { name: "sheenStrength", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Edge sheen",
      description: "Pearlescent light along the edges.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.4 },
    },
    { name: "background", type: "color", default: "#020206",
      label: "Background",
      description: "Color behind the ribbons.",
      group: "Color",
      advanced: true,
      random: false,
    },
  ],
});
