import { manifest } from '../../../shared/manifest';

export const liquidChromeManifest = manifest({
  id: "liquid-chrome",
  title: "Liquid Chrome",
  category: "Abstract",
  description: "Broad studio lights ripple across a slowly undulating metallic surface.",
  fragment: "shader.glsl",
  uniforms: [
    {"name": "reflectionWidth", "type": "float", "default": 1, "min": 0.3, "max": 3, "step": 0.01, "label": "Reflection width", "description": "Width of the bright reflected studio strip.", "group": "Color", "advanced": true, "random": false},
    {"name": "reflectionStrength", "type": "float", "default": 1, "min": 0, "max": 2, "step": 0.01, "label": "Reflection intensity", "description": "Strength of the narrow studio reflection.", "group": "Color", "advanced": true, "random": false},
    {"name": "highlightColor", "type": "color", "default": "#ffffff", "label": "Studio light", "description": "Tint of the narrow reflected light.", "group": "Color", "advanced": true, "colorRole": "onSurface"},

    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "scale", type: "float", default: 2, min: 0.5, max: 4, step: 0.01,
      label: "Ripple scale",
      description: "Spatial frequency of the metal ripples.",
      group: "Shape",
      random: {"min": 1.48, "max": 2.52},
    },
    { name: "roughness", type: "float", default: 0.25, min: 0.05, max: 1, step: 0.01,
      label: "Roughness",
      description: "Softness of reflected light bands.",
      group: "Shape",
      random: {"min": 0.11, "max": 0.39},
    },
    { name: "distortion", type: "float", default: 0.6, min: 0, max: 1.5, step: 0.01,
      label: "Distortion",
      description: "Depth of the secondary surface ripples.",
      group: "Shape",
      random: {"min": 0.38, "max": 0.82},
    },
    { name: "lightAngle", type: "float", default: 25, min: -180, max: 180, step: 1,
      label: "Light angle",
      unit: "°",
      description: "Orientation of the reflected studio lights.",
      group: "Color",
      random: {"min": -29.0, "max": 79.0},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#d0dce7",
      label: "Metal tint",
      description: "Color of the metal tint.",
      group: "Color",
      colorRole: "primary",
    },
    { name: "color2", type: "color", default: "#9cafd4",
      label: "Reflection tint",
      description: "Color of the reflection tint.",
      group: "Color",
      colorRole: "secondary",
    },
    { name: "background", type: "color", default: "#101624",
      label: "Shadow",
      description: "Color of the shadow.",
      group: "Color",
      random: false,
      colorRole: "surface",
    },
  ],
});
