import { manifest } from '../../../shared/manifest';

export const opalFilmManifest = manifest({
  id: "opal-film",
  title: "Opal Film",
  category: "Abstract",
  description: "Pearlescent bands glide over a gently flexing, luminous surface.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "scale", type: "float", default: 1.6, min: 0.5, max: 4, step: 0.01,
      label: "Surface scale",
      description: "Spatial frequency of the folds.",
      group: "Shape",
      random: {"min": 1.08, "max": 2.12},
    },
    { name: "iridescence", type: "float", default: 0.75, min: 0, max: 1.5, step: 0.01,
      label: "Iridescence",
      description: "Strength of the shifting spectral colors.",
      group: "Color",
      random: {"min": 0.53, "max": 0.97},
    },
    { name: "distortion", type: "float", default: 0.65, min: 0, max: 1.5, step: 0.01,
      label: "Surface distortion",
      description: "Amount of irregular bending in the film.",
      group: "Shape",
      random: {"min": 0.43, "max": 0.88},
    },
    { name: "sheen", type: "float", default: 0.7, min: 0, max: 1.5, step: 0.01,
      label: "Sheen",
      description: "Intensity of pearly reflections.",
      group: "Color",
      random: {"min": 0.47, "max": 0.92},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#efa8cc",
      label: "Primary color",
      description: "Primary color of the effect.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#8fcfe7",
      label: "Secondary color",
      description: "Secondary color of the effect.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#121826",
      label: "Background",
      description: "Base color behind the effect.",
      group: "Color",
      random: false,
    },
  ],
});
