import { manifest } from '../../../shared/manifest';

export const opalFilmManifest = manifest({
  id: "opal-film",
  title: "Opal Film",
  category: "Abstract",
  description: "Pearlescent bands glide over a gently flexing, luminous surface.",
  fragment: "shader.glsl",
  uniforms: [
    {"name": "evolutionRate", "type": "float", "default": 1, "min": 0, "max": 3, "step": 0.01, "label": "Surface evolution", "description": "Rate of fine surface change relative to the moving color bands.", "group": "Motion", "advanced": true, "random": false},
    {"name": "highlightColor", "type": "color", "default": "#ffffff", "label": "Pearl sheen", "description": "Tint of the bright pearlescent reflections.", "group": "Color", "advanced": true, "colorRole": "onSurface"},

    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "scale", type: "float", default: 1.6, min: 0.5, max: 4, step: 0.01,
      label: "Surface scale",
      description: "Spatial frequency of the folds.",
      group: "Shape",
      random: {"min": 1.08, "max": 2.12},
    },
    { name: "iridescence", type: "float", default: 0.75, min: 0, max: 1.5, step: 0.01,
      label: "Iridescence",
      description: "Strength of the shifting spectral colors.",
      group: "Color",
      random: {"min": 0.53, "max": 0.97},
    },
    { name: "distortion", type: "float", default: 0.65, min: 0, max: 1.5, step: 0.01,
      label: "Surface distortion",
      description: "Amount of irregular bending in the film.",
      group: "Shape",
      random: {"min": 0.43, "max": 0.88},
    },
    { name: "sheen", type: "float", default: 0.7, min: 0, max: 1.5, step: 0.01,
      label: "Sheen",
      description: "Intensity of pearly reflections.",
      group: "Color",
      random: {"min": 0.47, "max": 0.92},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#efa8cc",
      label: "Film tint",
      description: "Color of the film tint.",
      group: "Color",
      colorRole: "primary",
    },
    { name: "color2", type: "color", default: "#8fcfe7",
      label: "Iridescent tint",
      description: "Color of the iridescent tint.",
      group: "Color",
      colorRole: "secondary",
    },
    { name: "background", type: "color", default: "#121826",
      label: "Shadow",
      description: "Color of the shadow.",
      group: "Color",
      random: false,
      colorRole: "surface",
    },
  ],
});
