import { manifest } from '../../../shared/manifest';

export const flowFieldManifest = manifest({
  id: "flow-field",
  title: "Flow Field",
  description: "Slow currents of luminous color.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.4, min: 0, max: 3, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "scale", type: "float", default: 1, min: 0.1, max: 10, step: 0.01,
      label: "Scale",
      description: "Spatial frequency of the pattern.",
      group: "Shape",
      random: { min: 0.1, max: 2.98 },
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Light intensity of this shader.",
      group: "Color",
      random: { min: 0.6, max: 1.2 },
    },
    { name: "trail", type: "bool", default: true,
      label: "Edge glow",
      description: "Add luminous highlights along the currents.",
      group: "Color",
    },
    { name: "palette", type: "select", default: "aurora",
      options: ["aurora","mono","duotone"],
      label: "Palette",
      description: "Choose the color treatment.",
      group: "Color",
    },
    { name: "color", type: "color", default: "#44ccff",
      label: "Primary color",
      description: "Choose the primary color of the palette.",
      group: "Color",
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "direction", type: "float", default: 0, min: -180, max: 180, step: 1,
      label: "Direction",
      description: "Rotate the direction of movement from its original path.",
      group: "Motion",
      advanced: true,
      unit: "°",
      random: { min: -72, max: 72 },
    },
    { name: "turbulence", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Turbulence",
      description: "How strongly the currents bend.",
      group: "Shape",
      advanced: true,
      random: { min: 0.6, max: 1.4 },
    },
    { name: "glowStrength", type: "float", default: 0.08, min: 0, max: 0.2, step: 0.005,
      label: "Glow strength",
      description: "Intensity of the luminous current edges.",
      group: "Color",
      advanced: true,
      random: { min: 0.04, max: 0.12 },
      visibleWhen: { name: "trail", value: 1 },
    },
    { name: "glowWidth", type: "float", default: 0.08, min: 0.03, max: 0.25, step: 0.005,
      label: "Glow width",
      description: "Softness and width of luminous edges.",
      group: "Shape",
      advanced: true,
      random: { min: 0.036, max: 0.124 },
      visibleWhen: { name: "trail", value: 1 },
    },
    { name: "background", type: "color", default: "#040814",
      label: "Background",
      description: "Color behind the currents.",
      group: "Color",
      advanced: true,
      random: false,
    },
    { name: "color2", type: "color", default: "#ad70ff",
      label: "Secondary color",
      description: "Second current color in the Duotone palette.",
      group: "Color",
      advanced: false,
      visibleWhen: { name: "palette", value: "duotone" },
    },
  ],
});
