import { manifest } from '../../../shared/manifest';

export const guillocheManifest = manifest({
  id: "guilloche",
  title: "Guilloché",
  category: "Abstract",
  description: "Fine interwoven curves slowly evolve like intricate ornamental engravings.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "symmetry", type: "int", default: 8, min: 3, max: 16, step: 1,
      label: "Symmetry",
      description: "Number of repeating lobes around each rosette.",
      group: "Shape",
      random: {"min": 6.05, "max": 9.95},
    },
    { name: "lineSpacing", type: "float", default: 0.018, min: 0.008, max: 0.035, step: 0.001,
      label: "Line spacing",
      description: "Distance between engraved curves.",
      group: "Shape",
      random: {"min": 0.014, "max": 0.022},
    },
    { name: "weave", type: "float", default: 0.65, min: 0, max: 1.2, step: 0.01,
      label: "Weave",
      description: "Depth of the interwoven oscillations.",
      group: "Shape",
      random: {"min": 0.47, "max": 0.83},
    },
    { name: "rotation", type: "float", default: 0.3, min: -1, max: 1, step: 0.01,
      label: "Rotation",
      description: "Direction and rate of the rosette rotation.",
      group: "Motion",
      random: {"min": 0.0, "max": 0.6},
    },
    { name: "lineWidth", type: "float", default: 1, min: 0.5, max: 2.5, step: 0.01,
      label: "Line width",
      description: "Thickness of the fine engraved lines.",
      group: "Shape",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#e8bd78",
      label: "Primary color",
      description: "Primary color of the effect.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#62bfc0",
      label: "Secondary color",
      description: "Secondary color of the effect.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#101722",
      label: "Background",
      description: "Base color behind the effect.",
      group: "Color",
      random: false,
    },
  ],
});
