import { manifest } from '../../../shared/manifest';

export const tidalCausticsManifest = manifest({
  id: "tidal-caustics",
  title: "Tidal Caustics",
  description: "Soft pools of refracted light wander across a tranquil seabed.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.25, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "scale", type: "float", default: 1, min: 0.4, max: 3, step: 0.01,
      label: "Scale",
      description: "Spatial frequency of the pattern.",
      group: "Shape",
      random: { min: 0.48, max: 1.52 },
    },
    { name: "focus", type: "float", default: 0.5, min: 0, max: 1, step: 0.01,
      label: "Focus",
      description: "Sharpness of the refracted light.",
      group: "Shape",
      random: { min: 0.3, max: 0.7 },
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Light intensity of this shader.",
      group: "Color",
      random: { min: 0.6, max: 1.2 },
    },
    { name: "color1", type: "color", default: "#06394d",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#71e5d0",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "layers", type: "int", default: 3, min: 1, max: 4, step: 1,
      label: "Layer count",
      description: "Number of overlapping light patterns.",
      group: "Shape",
      advanced: true,
      random: { min: 2.4, max: 3.6 },
    },
    { name: "distortion", type: "float", default: 0.7, min: 0, max: 1.5, step: 0.01,
      label: "Distortion",
      description: "Strength of the underwater warping.",
      group: "Shape",
      advanced: true,
      random: { min: 0.4, max: 1 },
    },
    { name: "complexity", type: "float", default: 0.5, min: 0, max: 1, step: 0.01,
      label: "Wave complexity",
      description: "Strength of smaller diagonal waves.",
      group: "Shape",
      advanced: true,
      random: { min: 0.3, max: 0.7 },
    },
    { name: "direction", type: "float", default: 0, min: -180, max: 180, step: 1,
      label: "Direction",
      description: "Rotate the direction of movement from its original path.",
      group: "Motion",
      advanced: true,
      unit: "°",
      random: { min: -72, max: 72 },
    },
    { name: "depthShading", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Depth shading",
      description: "Variation in the seabed shading.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.4 },
    },
  ],
});
