import { manifest } from '../../../shared/manifest';

export const starDriftManifest = manifest({
  id: "star-drift",
  title: "Star Drift",
  category: 'Space',
  description: "Layers of softly glowing stars glide through a deep night sky.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "density", type: "float", default: 1, min: 0.4, max: 2, step: 0.01,
      label: "Density",
      description: "Amount of particles in the scene.",
      group: "Shape",
      random: { min: 0.68, max: 1.32 },
    },
    { name: "twinkle", type: "float", default: 0.3, min: 0, max: 1, step: 0.01,
      label: "Twinkle",
      description: "Amount of gradual star brightness variation.",
      group: "Motion",
      random: { min: 0.1, max: 0.5 },
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Light intensity of this shader.",
      group: "Color",
      random: { min: 0.6, max: 1.2 },
    },
    { name: "color1", type: "color", default: "#a9d6ff",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#ffe3bd",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "starSize", type: "float", default: 1, min: 0.5, max: 2, step: 0.01,
      label: "Star size",
      description: "Size of the bright star cores.",
      group: "Shape",
      advanced: true,
      random: { min: 0.7, max: 1.3 },
    },
    { name: "glowAmount", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Glow amount",
      description: "Soft halo surrounding each star.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.4 },
    },
    { name: "direction", type: "float", default: 0, min: -180, max: 180, step: 1,
      label: "Direction",
      description: "Rotate the direction of movement from its original path.",
      group: "Motion",
      advanced: true,
      unit: "°",
      random: { min: -72, max: 72 },
    },
    { name: "parallax", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Parallax",
      description: "Difference in drift speed between star layers.",
      group: "Motion",
      advanced: true,
      random: { min: 0.6, max: 1.4 },
    },
    { name: "twinkleRate", type: "float", default: 1, min: 0, max: 3, step: 0.01,
      label: "Twinkle rate",
      description: "Relative rate of the gentle brightness changes.",
      group: "Motion",
      advanced: true,
      random: { min: 0.4, max: 1.6 },
    },
    { name: "background", type: "color", default: "#010205",
      label: "Background",
      description: "Base color of the night sky.",
      group: "Color",
      advanced: true,
      random: false,
    },
  ],
});
