import { manifest } from '../../../shared/manifest';

export const floatingWindowsManifest = manifest({
  id: "floating-windows",
  title: "Floating Windows",
  category: "Geometric",
  description: "Drifting circles and rounded windows reveal a shared wash of slowly moving color.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.18, max: 0.4 },
    },
    { name: "windowCount", type: "int", default: 4, min: 2, max: 6, step: 1,
      label: "Windows",
      description: "Number of openings into the shared color field.",
      group: "Shape",
      random: { min: 2, max: 6 },
    },
    { name: "size", type: "float", default: 0.19, min: 0.1, max: 0.29, step: 0.01,
      label: "Window size",
      description: "Radius of the circular and rounded openings.",
      group: "Shape",
      random: { min: 0.16, max: 0.23 },
    },
    { name: "travel", type: "float", default: 0.65, min: 0, max: 1.4, step: 0.01,
      label: "Travel",
      description: "Distance the windows drift from their resting positions.",
      group: "Motion",
      random: { min: 0.4, max: 0.85 },
    },
    { name: "fieldRate", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Color drift",
      description: "Speed of the gradient moving behind the windows.",
      group: "Motion",
      random: { min: 0.6, max: 1.3 },
    },
    { name: "color1", type: "color", default: "#e1ac99",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#a99fd0",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#79aaa7",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#252d3b",
      label: "Background",
      description: "Base color behind the shapes and between their edges.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: { min: 0.7, max: 1.1 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      random: { min: 0.7, max: 1.15 },
      advanced: true,
    },
  ],
});
