import { manifest } from '../../../shared/manifest';

export const inkBloomManifest = manifest({
  id: "ink-bloom",
  title: "Ink Bloom",
  category: "Ambient",
  description: "Feathery clouds of pigment unfurl through softly lit paper.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "scale", type: "float", default: 2, min: 0.5, max: 4, step: 0.01,
      label: "Bloom scale",
      description: "Spatial frequency of the pigment clouds.",
      group: "Shape",
      random: {"min": 1.48, "max": 2.52},
    },
    { name: "curl", type: "float", default: 0.85, min: 0, max: 1.8, step: 0.01,
      label: "Curl",
      description: "Amount of swirling distortion.",
      group: "Shape",
      random: {"min": 0.58, "max": 1.12},
    },
    { name: "density", type: "float", default: 0.65, min: 0.15, max: 1.3, step: 0.01,
      label: "Pigment density",
      description: "Amount of ink suspended in the background.",
      group: "Shape",
      random: {"min": 0.48, "max": 0.82},
    },
    { name: "feather", type: "float", default: 0.6, min: 0, max: 1, step: 0.01,
      label: "Feather detail",
      description: "Fine tendrils along the cloud edges.",
      group: "Shape",
      advanced: true,
      random: {"min": 0.45, "max": 0.75},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#192546",
      label: "Primary color",
      description: "Primary color of the effect.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#9a526f",
      label: "Secondary color",
      description: "Secondary color of the effect.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#e9e1d0",
      label: "Background",
      description: "Base color behind the effect.",
      group: "Color",
      random: false,
    },
  ],
});
