import { manifest } from '../../../shared/manifest';

export const softApertureManifest = manifest({
  id: "soft-aperture",
  title: "Soft Aperture",
  category: "Ambient",
  description: "Offset rounded openings breathe slowly through washes of lilac, periwinkle, and cream.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      advanced: false,
      random: {"min":0.18,"max":0.4},
    },
    { name: "layers", type: "int", default: 6, min: 3, max: 8, step: 1,
      label: "Openings",
      description: "Number of nested rounded openings.",
      group: "Shape",
      random: {"min":3,"max":8},
    },
    { name: "roundness", type: "float", default: 0.7, min: 0.1, max: 1, step: 0.01,
      label: "Roundness",
      description: "Curvature of the corners of each opening.",
      group: "Shape",
      advanced: false,
      random: {"min":0.5,"max":0.95},
    },
    { name: "spacing", type: "float", default: 0.78, min: 0.65, max: 0.86, step: 0.01,
      label: "Opening ratio",
      description: "Size of each opening relative to the previous one.",
      group: "Shape",
      advanced: false,
      random: {"min":0.72,"max":0.82},
    },
    { name: "breathing", type: "float", default: 0.6, min: 0, max: 1.5, step: 0.01,
      label: "Breathing",
      description: "Amount of slow expansion and center movement.",
      group: "Motion",
      advanced: false,
      random: {"min":0.35,"max":0.9},
    },
    { name: "color1", type: "color", default: "#a897c4",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#8295bc",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#eadac0",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#34334e",
      label: "Background",
      description: "Color of the space around the composition.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: {"min":0.7,"max":1.1},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min":0.7,"max":1.15},
    },
  ],
});
