import { manifest } from '../../../shared/manifest';

export const eclipseStudyManifest = manifest({
  id: "eclipse-study",
  title: "Eclipse Study",
  category: "Ambient",
  description: "Two enormous gradient discs pass across dusk, revealing a changing peach crescent.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      advanced: false,
      random: {"min":0.18,"max":0.4},
    },
    { name: "size", type: "float", default: 0.38, min: 0.2, max: 0.6, step: 0.01,
      label: "Disc size",
      description: "Radius of the larger disc.",
      group: "Shape",
      advanced: false,
      random: {"min":0.32,"max":0.46},
    },
    { name: "separation", type: "float", default: 0.85, min: 0.2, max: 1.5, step: 0.01,
      label: "Separation",
      description: "Maximum distance between the disc centers.",
      group: "Shape",
      advanced: false,
      random: {"min":0.65,"max":1.1},
    },
    { name: "softness", type: "float", default: 0.006, min: 0.002, max: 0.06, step: 0.002,
      label: "Edge softness",
      description: "Softness of the disc silhouettes.",
      group: "Shape",
      advanced: false,
      random: {"min":0.006,"max":0.026},
    },
    { name: "drift", type: "float", default: 0.6, min: 0, max: 1.5, step: 0.01,
      label: "Drift",
      description: "Distance traveled by the whole composition.",
      group: "Motion",
      advanced: false,
      random: {"min":0.3,"max":1},
    },
    { name: "color1", type: "color", default: "#eab395",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#975e79",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#423b65",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#171c33",
      label: "Background",
      description: "Color of the space around the composition.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: {"min":0.7,"max":1.1},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min":0.7,"max":1.15},
    },
  ],
});
