import { manifest } from '../../../shared/manifest';

export const phosphorGardenManifest = manifest({
  id: "phosphor-garden",
  title: "Phosphor Garden",
  category: "Ambient",
  description: "Luminous stems unfurl as gentle pulses travel toward their growing tips.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "stemCount", type: "int", default: 12, min: 4, max: 20, step: 1,
      label: "Stem count",
      description: "Number of luminous stems.",
      group: "Shape",
      random: {"min": 9.6, "max": 14.4},
    },
    { name: "curvature", type: "float", default: 0.65, min: 0, max: 1.5, step: 0.01,
      label: "Curvature",
      description: "Amount the stems bend and sway.",
      group: "Shape",
      random: {"min": 0.43, "max": 0.88},
    },
    { name: "pulseRate", type: "float", default: 0.8, min: 0, max: 2, step: 0.01,
      label: "Pulse rate",
      description: "Rate of light traveling up the stems.",
      group: "Motion",
      random: {"min": 0.5, "max": 1.1},
    },
    { name: "growth", type: "float", default: 0.7, min: 0.2, max: 1, step: 0.01,
      label: "Growth",
      description: "Height and reach of the growing stems.",
      group: "Shape",
      random: {"min": 0.58, "max": 0.82},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#5ee7aa",
      label: "Primary color",
      description: "Primary color of the effect.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#5a9bdc",
      label: "Secondary color",
      description: "Secondary color of the effect.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#07121b",
      label: "Background",
      description: "Base color behind the effect.",
      group: "Color",
      random: false,
    },
  ],
});
