import { manifest } from '../../../shared/manifest';

export const rainGlassManifest = manifest({
  id: "rain-glass",
  title: "Rain Glass",
  category: "Water",
  description: "Slow droplets trail down glass over blurred pools of nighttime color.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "density", type: "float", default: 0.7, min: 0.1, max: 1, step: 0.01,
      label: "Rain density",
      description: "Proportion of glass covered by moving drops.",
      group: "Shape",
      random: {"min": 0.56, "max": 0.83},
    },
    { name: "streakLength", type: "float", default: 0.65, min: 0.1, max: 1, step: 0.01,
      label: "Streak length",
      description: "Length of the wet trails behind droplets.",
      group: "Shape",
      random: {"min": 0.52, "max": 0.79},
    },
    { name: "blur", type: "float", default: 0.65, min: 0.1, max: 1, step: 0.01,
      label: "Background blur",
      description: "Softness of distant lights.",
      group: "Shape",
      random: {"min": 0.52, "max": 0.79},
    },
    { name: "refraction", type: "float", default: 0.6, min: 0, max: 1.5, step: 0.01,
      label: "Refraction",
      description: "Amount the droplets bend the lights.",
      group: "Shape",
      advanced: true,
      random: {"min": 0.38, "max": 0.82},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#e8ac6c",
      label: "Primary color",
      description: "Primary color of the effect.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#639dcb",
      label: "Secondary color",
      description: "Secondary color of the effect.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#0a1425",
      label: "Background",
      description: "Base color behind the effect.",
      group: "Color",
      random: false,
    },
  ],
});
