import { manifest } from '../../../shared/manifest';

export const colorMobileManifest = manifest({
  id: "color-mobile",
  title: "Color Mobile",
  category: "Ambient",
  description: "Semicircles, rounded bars, and discs rock gently in an open field of color.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      advanced: false,
      random: {"min":0.18,"max":0.4},
    },
    { name: "shapeCount", type: "int", default: 6, min: 3, max: 8, step: 1,
      label: "Shapes",
      description: "Number of pieces in the mobile.",
      group: "Shape",
      random: {"min":3,"max":8},
    },
    { name: "size", type: "float", default: 1, min: 0.5, max: 1.6, step: 0.01,
      label: "Size",
      description: "Scale of each suspended shape.",
      group: "Shape",
      advanced: false,
      random: {"min":0.8,"max":1.2},
    },
    { name: "sway", type: "float", default: 0.8, min: 0, max: 1.5, step: 0.01,
      label: "Rocking",
      description: "Angle through which each piece rocks.",
      group: "Motion",
      advanced: false,
      random: {"min":0.5,"max":1},
    },
    { name: "travel", type: "float", default: 0.6, min: 0, max: 1.5, step: 0.01,
      label: "Travel",
      description: "Distance pieces drift from their resting positions.",
      group: "Motion",
      advanced: false,
      random: {"min":0.3,"max":0.85},
    },
    { name: "color1", type: "color", default: "#e4ca84",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#cc8c82",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#789598",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#252d3b",
      label: "Background",
      description: "Color of the space around the composition.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: {"min":0.7,"max":1.1},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min":0.7,"max":1.15},
    },
  ],
});
