import { manifest } from '../../../shared/manifest';

export const kineticTilesManifest = manifest({
  id: "kinetic-tiles",
  title: "Kinetic Tiles",
  category: "Digital",
  description: "Rounded tiles turn and slide in coordinated waves across a quiet grid.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "tileScale", type: "float", default: 5, min: 2, max: 10, step: 0.01,
      label: "Tile density",
      description: "Number of tiles per screen height.",
      group: "Shape",
      random: {"min": 3.8, "max": 6.2},
    },
    { name: "spacing", type: "float", default: 0.16, min: 0.04, max: 0.4, step: 0.01,
      label: "Spacing",
      description: "Gap between neighboring tiles.",
      group: "Shape",
      random: {"min": 0.11, "max": 0.21},
    },
    { name: "rotation", type: "float", default: 1, min: 0, max: 1.5, step: 0.01,
      label: "Rotation",
      description: "Amount each tile turns during a wave.",
      group: "Motion",
      random: {"min": 0.78, "max": 1.23},
    },
    { name: "waveDelay", type: "float", default: 0.65, min: 0, max: 2, step: 0.01,
      label: "Wave delay",
      description: "Phase offset between adjacent tiles.",
      group: "Motion",
      random: {"min": 0.35, "max": 0.95},
    },
    { name: "slide", type: "float", default: 0.45, min: 0, max: 1, step: 0.01,
      label: "Slide",
      description: "Distance tiles shift within their cells.",
      group: "Motion",
      advanced: true,
      random: {"min": 0.3, "max": 0.6},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#e9b56c",
      label: "Primary color",
      description: "Primary color of the effect.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#67b6bb",
      label: "Secondary color",
      description: "Secondary color of the effect.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#111d2b",
      label: "Background",
      description: "Base color behind the effect.",
      group: "Color",
      random: false,
    },
  ],
});
