import { manifest } from '../../../shared/manifest';

export const emberDriftManifest = manifest({
  id: "ember-drift",
  title: "Ember Drift",
  category: 'Ambient',
  description: "Warm motes rise and softly fade against a smoky night.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "density", type: "float", default: 0.7, min: 0.1, max: 1, step: 0.01,
      label: "Density",
      description: "Amount of particles in the scene.",
      group: "Shape",
      random: { min: 0.52, max: 0.88 },
    },
    { name: "glow", type: "float", default: 0.5, min: 0, max: 1, step: 0.01,
      label: "Glow",
      description: "Size and intensity of the soft particle halos.",
      group: "Color",
      random: { min: 0.3, max: 0.7 },
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Light intensity of this shader.",
      group: "Color",
      random: { min: 0.6, max: 1.2 },
    },
    { name: "color1", type: "color", default: "#ff9b48",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#ffd99a",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "emberSize", type: "float", default: 1, min: 0.5, max: 3, step: 0.01,
      label: "Ember size",
      description: "Size of the glowing motes.",
      group: "Shape",
      advanced: true,
      random: { min: 0.5, max: 1.5 },
    },
    { name: "sizeVariation", type: "float", default: 1, min: 0, max: 1.5, step: 0.01,
      label: "Size variation",
      description: "Difference in size between individual motes.",
      group: "Shape",
      advanced: true,
      random: { min: 0.7, max: 1.3 },
    },
    { name: "direction", type: "float", default: 0, min: -180, max: 180, step: 1,
      label: "Rise direction",
      description: "Rotate the particle paths; zero rises upward.",
      group: "Motion",
      advanced: true,
      unit: "°",
      random: { min: -72, max: 72 },
    },
    { name: "wander", type: "float", default: 0.045, min: 0, max: 0.15, step: 0.005,
      label: "Sideways wander",
      description: "Amount of gentle sideways movement.",
      group: "Motion",
      advanced: true,
      random: { min: 0.015, max: 0.075 },
    },
    { name: "fadeDuration", type: "float", default: 1, min: 0.3, max: 1.8, step: 0.01,
      label: "Fade duration",
      description: "Relative time spent fading at the start and end of each lifetime.",
      group: "Motion",
      advanced: true,
      random: { min: 0.7, max: 1.3 },
    },
    { name: "hazeStrength", type: "float", default: 0.035, min: 0, max: 0.15, step: 0.005,
      label: "Haze strength",
      description: "Warm smoky light behind the embers.",
      group: "Color",
      advanced: true,
      random: { min: 0.005, max: 0.065 },
    },
    { name: "background", type: "color", default: "#030102",
      label: "Background",
      description: "Base color behind the embers.",
      group: "Color",
      advanced: true,
      random: false,
    },
  ],
});
