import { manifest } from '../../../shared/manifest';

export const tidalCutoutsManifest = manifest({
  id: "tidal-cutouts",
  title: "Tidal Cutouts",
  category: "Ambient",
  description: "Broad layers of sage, sand, and muted blue rise and fall like a paper landscape.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      advanced: false,
      random: {"min":0.18,"max":0.4},
    },
    { name: "layers", type: "int", default: 4, min: 3, max: 6, step: 1,
      label: "Layers",
      description: "Number of overlapping landscape silhouettes.",
      group: "Shape",
      random: {"min":3,"max":6},
    },
    { name: "waveHeight", type: "float", default: 0.09, min: 0.02, max: 0.2, step: 0.01,
      label: "Wave height",
      description: "Height of the rolling cutout boundaries.",
      group: "Shape",
      advanced: false,
      random: {"min":0.06,"max":0.13},
    },
    { name: "wavelength", type: "float", default: 1, min: 0.4, max: 2, step: 0.01,
      label: "Wavelength",
      description: "Horizontal width of the broad curves.",
      group: "Shape",
      advanced: false,
      random: {"min":0.8,"max":1.4},
    },
    { name: "sway", type: "float", default: 0.7, min: 0, max: 1.5, step: 0.01,
      label: "Tide",
      description: "Amount of slow vertical movement.",
      group: "Motion",
      advanced: false,
      random: {"min":0.4,"max":1},
    },
    { name: "color1", type: "color", default: "#a4b5a4",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#dcc8a7",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#627f92",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#e8dfcf",
      label: "Background",
      description: "Color of the space around the composition.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: {"min":0.7,"max":1.1},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min":0.7,"max":1.15},
    },
  ],
});
