import { manifest } from '../../../shared/manifest';

export const gradientBlobsManifest = manifest({
  id: "gradient-blobs",
  title: "Gradient Blobs",
  description: "Glowing gradient blobs float, merge, and gently pull apart.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.4, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "size", type: "float", default: 0.19, min: 0.08, max: 0.35, step: 0.01,
      label: "Size",
      description: "Base radius of each blob.",
      group: "Shape",
      random: { min: 0.136, max: 0.244 },
    },
    { name: "softness", type: "float", default: 0.45, min: 0.05, max: 1, step: 0.01,
      label: "Softness",
      description: "Softness of the shape edges.",
      group: "Shape",
      random: { min: 0.26, max: 0.64 },
    },
    { name: "count", type: "int", default: 5, min: 2, max: 8, step: 1,
      label: "Blob count",
      description: "Number of moving blobs.",
      group: "Shape",
      random: { min: 3.8, max: 6.2 },
    },
    { name: "color1", type: "color", default: "#9f63ff",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#ff719a",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#50dbe8",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#0b1029",
      label: "Background",
      description: "Choose the background of the palette.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: { min: 0.6, max: 1.2 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "movementRange", type: "float", default: 1, min: 0, max: 1.3, step: 0.01,
      label: "Movement range",
      description: "Distance the blobs travel from the center.",
      group: "Motion",
      advanced: true,
      random: { min: 0.74, max: 1.26 },
    },
    { name: "stretchX", type: "float", default: 1, min: 0.5, max: 2, step: 0.01,
      label: "Horizontal stretch",
      description: "Stretch each blob horizontally.",
      group: "Shape",
      advanced: true,
      random: { min: 0.7, max: 1.3 },
    },
    { name: "stretchY", type: "float", default: 1, min: 0.5, max: 2, step: 0.01,
      label: "Vertical stretch",
      description: "Stretch each blob vertically.",
      group: "Shape",
      advanced: true,
      random: { min: 0.7, max: 1.3 },
    },
    { name: "sizeVariation", type: "float", default: 0, min: 0, max: 0.5, step: 0.01,
      label: "Size variation",
      description: "Difference in size between individual blobs.",
      group: "Shape",
      advanced: true,
      random: { min: 0, max: 0.1 },
    },
    { name: "breathing", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Breathing",
      description: "Amount of slow size pulsation.",
      group: "Motion",
      advanced: true,
      random: { min: 0.6, max: 1.4 },
    },
    { name: "haloStrength", type: "float", default: 0.16, min: 0, max: 0.5, step: 0.01,
      label: "Halo strength",
      description: "Soft light surrounding the blobs.",
      group: "Color",
      advanced: true,
      random: { min: 0.06, max: 0.26 },
    },
  ],
});
