import { manifest } from '../../../shared/manifest';

export const chromaticOverlapManifest = manifest({
  id: "chromatic-overlap",
  title: "Chromatic Overlap",
  category: "Ambient",
  description: "Translucent circles and capsules drift together, mixing apricot, lavender, and teal.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      advanced: false,
      random: {"min":0.18,"max":0.4},
    },
    { name: "size", type: "float", default: 1, min: 0.5, max: 1.6, step: 0.01,
      label: "Size",
      description: "Scale of the circles and capsule.",
      group: "Shape",
      advanced: false,
      random: {"min":0.8,"max":1.2},
    },
    { name: "softness", type: "float", default: 0.012, min: 0.002, max: 0.08, step: 0.002,
      label: "Edge softness",
      description: "Width of the soft boundary around each shape.",
      group: "Shape",
      advanced: false,
      random: {"min":0.012,"max":0.032},
    },
    { name: "travel", type: "float", default: 1, min: 0, max: 1.5, step: 0.01,
      label: "Orbit range",
      description: "Distance each shape travels along its slow orbit.",
      group: "Motion",
      advanced: false,
      random: {"min":0.65,"max":1.2},
    },
    { name: "opacity", type: "float", default: 0.8, min: 0.2, max: 1, step: 0.01,
      label: "Pigment",
      description: "Strength of the translucent colors and their overlaps.",
      group: "Color",
      advanced: false,
      random: {"min":0.65,"max":0.9},
    },
    { name: "color1", type: "color", default: "#efb18c",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#b5a3dc",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#74bdb5",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#f0e8db",
      label: "Background",
      description: "Color of the space around the composition.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: {"min":0.7,"max":1.1},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min":0.7,"max":1.15},
    },
  ],
});
