import { manifest } from '../../../shared/manifest';

export const petalHoursManifest = manifest({
  id: "petal-hours",
  title: "Petal Hours",
  category: "Geometric",
  description: "Broad gradient petals slowly lean and lengthen around a quiet off-center opening.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.18, max: 0.4 },
    },
    { name: "petals", type: "int", default: 5, min: 4, max: 6, step: 1,
      label: "Petals",
      description: "Number of broad petals around the opening.",
      group: "Shape",
      random: { min: 4, max: 6 },
    },
    { name: "size", type: "float", default: 1, min: 0.6, max: 1.4, step: 0.01,
      label: "Size",
      description: "Scale of the petal composition.",
      group: "Shape",
      random: { min: 0.85, max: 1.15 },
    },
    { name: "opening", type: "float", default: 0.08, min: 0.02, max: 0.18, step: 0.01,
      label: "Opening",
      description: "Radius of the negative space between the petals.",
      group: "Shape",
      random: { min: 0.05, max: 0.12 },
    },
    { name: "sway", type: "float", default: 0.7, min: 0, max: 1.3, step: 0.01,
      label: "Sway",
      description: "Amount of gentle petal leaning and lengthening.",
      group: "Motion",
      random: { min: 0.4, max: 0.9 },
    },
    { name: "color1", type: "color", default: "#d39c97",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#a58cae",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#e4ce95",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#363344",
      label: "Background",
      description: "Base color behind the shapes and between their edges.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: { min: 0.7, max: 1.1 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      random: { min: 0.7, max: 1.15 },
      advanced: true,
    },
  ],
});
