import { manifest } from '../../../shared/manifest';

export const quietArchesManifest = manifest({
  id: "quiet-arches",
  title: "Quiet Arches",
  category: "Geometric",
  description: "Nested arches in clay, rose, and plum slowly widen and slide across one another.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      advanced: false,
      random: {"min":0.18,"max":0.4},
    },
    { name: "archCount", type: "int", default: 6, min: 3, max: 8, step: 1,
      label: "Arches",
      description: "Number of nested arch silhouettes.",
      group: "Shape",
      random: {"min":3,"max":8},
    },
    { name: "size", type: "float", default: 1, min: 0.6, max: 1.5, step: 0.01,
      label: "Size",
      description: "Scale of the arch composition.",
      group: "Shape",
      advanced: false,
      random: {"min":0.85,"max":1.2},
    },
    { name: "spacing", type: "float", default: 0.12, min: 0.07, max: 0.18, step: 0.01,
      label: "Spacing",
      description: "Width of the bands between arches.",
      group: "Shape",
      advanced: false,
      random: {"min":0.1,"max":0.14},
    },
    { name: "sway", type: "float", default: 0.65, min: 0, max: 1.2, step: 0.01,
      label: "Sway",
      description: "Amount of slow sideways movement and widening.",
      group: "Motion",
      advanced: false,
      random: {"min":0.35,"max":0.85},
    },
    { name: "color1", type: "color", default: "#bb806e",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#d2a29d",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#69516d",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#242339",
      label: "Background",
      description: "Color of the space around the composition.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: {"min":0.7,"max":1.1},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min":0.7,"max":1.15},
    },
  ],
});
