import { manifest } from '../../../shared/manifest';

export const magneticFilamentsManifest = manifest({
  id: "magnetic-filaments",
  title: "Magnetic Filaments",
  category: "Abstract",
  description: "Fine luminous field lines bend around slowly orbiting magnetic poles.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "poleCount", type: "int", default: 4, min: 2, max: 6, step: 1,
      label: "Pole count",
      description: "Number of moving poles shaping the field.",
      group: "Shape",
      random: {"min": 3.4, "max": 4.6},
    },
    { name: "poleSpacing", type: "float", default: 0.32, min: 0.1, max: 0.65, step: 0.01,
      label: "Pole spacing",
      description: "Distance of the poles from the center.",
      group: "Shape",
      random: {"min": 0.24, "max": 0.4},
    },
    { name: "lineDensity", type: "float", default: 16, min: 6, max: 32, step: 0.01,
      label: "Line density",
      description: "Number of luminous field contours.",
      group: "Shape",
      random: {"min": 12.1, "max": 19.9},
    },
    { name: "curvature", type: "float", default: 0.65, min: 0, max: 1.5, step: 0.01,
      label: "Curvature",
      description: "Strength of the secondary field distortion.",
      group: "Shape",
      random: {"min": 0.43, "max": 0.88},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#68d3d6",
      label: "Primary color",
      description: "Primary color of the effect.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#b992f4",
      label: "Secondary color",
      description: "Secondary color of the effect.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#090f20",
      label: "Background",
      description: "Base color behind the effect.",
      group: "Color",
      random: false,
    },
  ],
});
