import { manifest } from '../../../shared/manifest';

export const plasmaManifest = manifest({
  id: "plasma",
  title: "Chromatic Plasma",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.65, min: 0, max: 3, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "scale", type: "float", default: 3.5, min: 0.5, max: 12, step: 0.01,
      label: "Scale",
      description: "Spatial frequency of the pattern.",
      group: "Shape",
      random: { min: 1.2, max: 5.8 },
    },
    { name: "contrast", type: "float", default: 1.15, min: 0.25, max: 2.5, step: 0.01,
      label: "Contrast",
      description: "Strength of the plasma wave interference.",
      group: "Shape",
      random: { min: 0.7, max: 1.6 },
    },
    { name: "palette", type: "select", default: "neon",
      options: ["neon","sunset","ice","custom"],
      label: "Palette",
      description: "Choose the color treatment.",
      group: "Color",
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: { min: 0.6, max: 1.2 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "direction", type: "float", default: 0, min: -180, max: 180, step: 1,
      label: "Direction",
      description: "Rotate the direction of movement from its original path.",
      group: "Motion",
      advanced: true,
      unit: "°",
      random: { min: -72, max: 72 },
    },
    { name: "distortion", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Wave distortion",
      description: "Strength of the diagonal wave pattern.",
      group: "Shape",
      advanced: true,
      random: { min: 0.6, max: 1.4 },
    },
    { name: "radialStrength", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Radial waves",
      description: "Strength of waves radiating from the center.",
      group: "Shape",
      advanced: true,
      random: { min: 0.6, max: 1.4 },
    },
    { name: "paletteOffset", type: "float", default: 0, min: -1, max: 1, step: 0.01,
      label: "Palette offset",
      description: "Shift colors along the selected palette.",
      group: "Color",
      advanced: true,
      random: { min: -0.4, max: 0.4 },
    },
    { name: "color1", type: "color", default: "#7051ef",
      label: "Custom shadow",
      description: "First color of the Custom palette.",
      group: "Color",
      advanced: false,
      visibleWhen: { name: "palette", value: "custom" },
    },
    { name: "color2", type: "color", default: "#ff8bb3",
      label: "Custom midtone",
      description: "Middle color of the Custom palette.",
      group: "Color",
      advanced: false,
      visibleWhen: { name: "palette", value: "custom" },
    },
    { name: "color3", type: "color", default: "#45dfcf",
      label: "Custom highlight",
      description: "Last color of the Custom palette.",
      group: "Color",
      advanced: false,
      visibleWhen: { name: "palette", value: "custom" },
    },
  ],
});
