import { manifest } from '../../../shared/manifest';

export const auroraVeilManifest = manifest({
  id: "aurora-veil",
  title: "Aurora Veil",
  category: 'Ambient',
  description: "Translucent ribbons of light ripple across a midnight gradient.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "waves", type: "float", default: 1.5, min: 0.5, max: 4, step: 0.01,
      label: "Waves",
      description: "Number of broad waves across the aurora.",
      group: "Shape",
      random: { min: 0.8, max: 2.2 },
    },
    { name: "spread", type: "float", default: 0.45, min: 0.1, max: 1, step: 0.01,
      label: "Spread",
      description: "Width of the translucent curtains.",
      group: "Shape",
      random: { min: 0.27, max: 0.63 },
    },
    { name: "brightness", type: "float", default: 1, min: 0.2, max: 2, step: 0.01,
      label: "Brightness",
      description: "Light intensity of this shader.",
      group: "Color",
      random: { min: 0.6, max: 1.2 },
    },
    { name: "color1", type: "color", default: "#38e8ba",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#9270ff",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "curtains", type: "int", default: 3, min: 1, max: 5, step: 1,
      label: "Curtain count",
      description: "Number of overlapping curtains.",
      group: "Shape",
      advanced: true,
      random: { min: 2.2, max: 3.8 },
    },
    { name: "verticalPosition", type: "float", default: 0, min: -0.4, max: 0.4, step: 0.01,
      label: "Vertical position",
      description: "Move the aurora up or down.",
      group: "Shape",
      advanced: true,
      random: { min: -0.16, max: 0.16 },
    },
    { name: "amplitude", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Wave amplitude",
      description: "Height of the rolling waves.",
      group: "Motion",
      advanced: true,
      random: { min: 0.6, max: 1.4 },
    },
    { name: "foldDetail", type: "float", default: 1, min: 0.2, max: 2, step: 0.01,
      label: "Fold detail",
      description: "Frequency of small folds within each curtain.",
      group: "Shape",
      advanced: true,
      random: { min: 0.64, max: 1.36 },
    },
    { name: "background", type: "color", default: "#02040d",
      label: "Lower sky",
      description: "Background color at the bottom.",
      group: "Color",
      advanced: true,
      random: false,
    },
    { name: "backgroundTop", type: "color", default: "#090e21",
      label: "Upper sky",
      description: "Background color at the top.",
      group: "Color",
      advanced: true,
      random: false,
    },
  ],
});
