import { manifest } from '../../../shared/manifest';

export const quietPleatsManifest = manifest({
  id: "quiet-pleats",
  title: "Quiet Pleats",
  category: "Geometric",
  description: "Wide bands of lavender, slate, and cream compress and expand like gently folded paper.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.18, max: 0.4 },
    },
    { name: "folds", type: "int", default: 7, min: 3, max: 12, step: 1,
      label: "Folds",
      description: "Number of broad folds across the shorter screen dimension.",
      group: "Shape",
      random: { min: 3, max: 12 },
    },
    { name: "angle", type: "float", default: -12, min: -90, max: 90, step: 0.01,
      label: "Angle",
      description: "Orientation of the pleats in degrees.",
      group: "Shape",
      random: { min: -25, max: 25 },
    },
    { name: "compression", type: "float", default: 0.65, min: 0, max: 1.2, step: 0.01,
      label: "Compression",
      description: "Amount of the wave that widens and narrows neighboring folds.",
      group: "Motion",
      random: { min: 0.4, max: 0.9 },
    },
    { name: "depth", type: "float", default: 0.3, min: 0.05, max: 0.6, step: 0.01,
      label: "Fold contrast",
      description: "Strength of the soft gradients across the pleats.",
      group: "Color",
      random: { min: 0.2, max: 0.4 },
    },
    { name: "color1", type: "color", default: "#b4a5c6",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#7d8b9d",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#e2d5be",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#444558",
      label: "Background",
      description: "Base color behind the shapes and between their edges.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: { min: 0.7, max: 1.1 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      random: { min: 0.7, max: 1.15 },
      advanced: true,
    },
  ],
});
