import { manifest } from '../../../shared/manifest';

export const tangramTideManifest = manifest({
  id: "tangram-tide",
  title: "Tangram Tide",
  category: "Geometric",
  description: "Triangles, trapezoids, and parallelograms glide and gently turn through open space.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.18, max: 0.4 },
    },
    { name: "pieces", type: "int", default: 7, min: 3, max: 9, step: 1,
      label: "Pieces",
      description: "Number of drifting polygon pieces.",
      group: "Shape",
      random: { min: 3, max: 9 },
    },
    { name: "size", type: "float", default: 0.11, min: 0.07, max: 0.22, step: 0.01,
      label: "Size",
      description: "Scale of each geometric piece.",
      group: "Shape",
      random: { min: 0.1, max: 0.16 },
    },
    { name: "travel", type: "float", default: 0.8, min: 0, max: 1.5, step: 0.01,
      label: "Travel",
      description: "Distance pieces glide from their resting positions.",
      group: "Motion",
      random: { min: 0.5, max: 1 },
    },
    { name: "turn", type: "float", default: 0.7, min: 0, max: 1.5, step: 0.01,
      label: "Turning",
      description: "Amount of gentle rotation.",
      group: "Motion",
      random: { min: 0.4, max: 0.9 },
    },
    { name: "color1", type: "color", default: "#cba98b",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#b68f9f",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#8babb2",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#2b3041",
      label: "Background",
      description: "Base color behind the shapes and between their edges.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: { min: 0.7, max: 1.1 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      random: { min: 0.7, max: 1.15 },
      advanced: true,
    },
  ],
});
