import { manifest } from '../../../shared/manifest';

export const islandHoursManifest = manifest({
  id: "island-hours",
  title: "Island Hours",
  category: "Ambient",
  description: "Organic islands swell gently as nested bands of sage, chalk, and turquoise drift within them.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.18, max: 0.4 },
    },
    { name: "islandCount", type: "int", default: 3, min: 1, max: 5, step: 1,
      label: "Islands",
      description: "Number of islands in the archipelago.",
      group: "Shape",
      random: { min: 1, max: 5 },
    },
    { name: "size", type: "float", default: 0.23, min: 0.12, max: 0.36, step: 0.01,
      label: "Size",
      description: "Radius of each island silhouette.",
      group: "Shape",
      random: { min: 0.19, max: 0.27 },
    },
    { name: "undulation", type: "float", default: 0.12, min: 0.02, max: 0.25, step: 0.01,
      label: "Coastline",
      description: "Amount of gentle irregularity around each island.",
      group: "Shape",
      random: { min: 0.07, max: 0.18 },
    },
    { name: "drift", type: "float", default: 0.7, min: 0, max: 1.3, step: 0.01,
      label: "Drift",
      description: "Amount of island breathing and inner-band movement.",
      group: "Motion",
      random: { min: 0.4, max: 0.95 },
    },
    { name: "color1", type: "color", default: "#9aafa0",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#ded9be",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#75a3a4",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#293b48",
      label: "Background",
      description: "Base color behind the shapes and between their edges.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: { min: 0.7, max: 1.1 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      random: { min: 0.7, max: 1.15 },
      advanced: true,
    },
  ],
});
