import { manifest } from '../../../shared/manifest';

export const interferenceManifest = manifest({
  id: "interference",
  title: "Orbital Interference",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.35, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "rings", type: "int", default: 18, min: 3, max: 48, step: 1,
      label: "Rings",
      description: "Density of the concentric rings.",
      group: "Shape",
      random: { min: 9, max: 27 },
    },
    { name: "softness", type: "float", default: 0.09, min: 0.01, max: 0.3, step: 0.01,
      label: "Softness",
      description: "Softness of the shape edges.",
      group: "Shape",
      random: { min: 0.032, max: 0.148 },
    },
    { name: "invert", type: "bool", default: false,
      label: "Invert",
      description: "Swap the bright and dark regions.",
      group: "Color",
    },
    { name: "color", type: "color", default: "#9d7cff",
      label: "Primary color",
      description: "Choose the primary color of the palette.",
      group: "Color",
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: { min: 0.6, max: 1.2 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "orbitRadius", type: "float", default: 0.38, min: 0, max: 0.8, step: 0.01,
      label: "Orbit radius",
      description: "Distance of the ring centers from the middle.",
      group: "Motion",
      advanced: true,
      random: { min: 0.22, max: 0.54 },
    },
    { name: "orbitStretch", type: "float", default: 1, min: 0.2, max: 2, step: 0.01,
      label: "Orbit stretch",
      description: "Vertical stretch of the orbital paths.",
      group: "Motion",
      advanced: true,
      random: { min: 0.64, max: 1.36 },
    },
    { name: "expansionRate", type: "float", default: 1, min: -2, max: 2, step: 0.01,
      label: "Ring expansion",
      description: "Relative rate and direction of ring travel.",
      group: "Motion",
      advanced: true,
      random: { min: 0.2, max: 1.8 },
    },
    { name: "lineThickness", type: "float", default: 0.02, min: 0.002, max: 0.08, step: 0.001,
      label: "Line thickness",
      description: "Width of the bright ring cores.",
      group: "Shape",
      advanced: true,
      random: { min: 0.0044, max: 0.0356 },
    },
    { name: "intersectionGlow", type: "float", default: 0.55, min: 0, max: 1, step: 0.01,
      label: "Intersection glow",
      description: "Brightness where the two ring systems intersect.",
      group: "Color",
      advanced: true,
      random: { min: 0.35, max: 0.75 },
    },
    { name: "background", type: "color", default: "#020307",
      label: "Background",
      description: "Color between the rings.",
      group: "Color",
      advanced: true,
      random: false,
    },
  ],
});
