// Curated list of well-known palettes exposed as pickable color schemes.
// `file` is relative to reference/. The generator reads color_01..color_16,
// background, foreground, cursor, and variant from each file.
// Optional `roles` overrides the ANSI-derived role colors for a palette.
export const palettes = [
  { id: 'dracula', name: 'Dracula', file: 'Dracula.yml' },
  { id: 'nord', name: 'Nord', file: 'Nord.yml' },
  { id: 'gruvbox-dark', name: 'Gruvbox Dark', file: 'Gruvbox Dark.yml' },
  { id: 'gruvbox-light', name: 'Gruvbox Light', file: 'Gruvbox Light.yml' },
  { id: 'solarized-dark', name: 'Solarized Dark', file: 'Solarized Dark.yml' },
  { id: 'solarized-light', name: 'Solarized Light', file: 'Solarized Light.yml' },
  { id: 'monokai', name: 'Monokai', file: 'Monokai.yml' },
  { id: 'one-dark', name: 'One Dark', file: 'One Dark.yml' },
  { id: 'tokyo-night', name: 'Tokyo Night', file: 'Tokyo Night Dark.yml' },
  { id: 'tokyo-night-storm', name: 'Tokyo Night Storm', file: 'TokyoNight Storm.yml' },
  { id: 'night-owl', name: 'Night Owl', file: 'Night Owl.yml' },
  { id: 'palenight', name: 'Palenight', file: 'Palenight.yml' },
  { id: 'zenburn', name: 'Zenburn', file: 'Zenburn.yml' },
  { id: 'ayu-dark', name: 'Ayu Dark', file: 'Ayu Dark.yml' },
  { id: 'ayu-mirage', name: 'Ayu Mirage', file: 'Ayu Mirage.yml' },
  { id: 'ayu-light', name: 'Ayu Light', file: 'Ayu Light.yml' },
  { id: 'rose-pine', name: 'Rosé Pine', file: 'Rose Pine.yml' },
  { id: 'rose-pine-moon', name: 'Rosé Pine Moon', file: 'Rose Pine Moon.yml' },
  { id: 'rose-pine-dawn', name: 'Rosé Pine Dawn', file: 'Rose Pine Dawn.yml' },
  { id: 'kanagawa-wave', name: 'Kanagawa Wave', file: 'Kanagawa Wave.yml' },
  { id: 'kanagawa-dragon', name: 'Kanagawa Dragon', file: 'Kanagawa Dragon.yml' },
  { id: 'kanagawa-lotus', name: 'Kanagawa Lotus', file: 'Kanagawa Lotus.yml' },
  { id: 'github-dark', name: 'GitHub Dark', file: 'GitHub Dark.yml' },
  { id: 'github-light', name: 'GitHub Light', file: 'Github Light.yml' },
  { id: 'material-dark', name: 'Material', file: 'Material Dark.yml' },
  { id: 'material-palenight', name: 'Material Palenight', file: 'Material Palenight.yml' },
  { id: 'everforest-dark', name: 'Everforest Dark', file: 'Everforest Dark.yml' },
  { id: 'everforest-light', name: 'Everforest Light', file: 'Everforest Light.yml' },
  { id: 'iceberg-dark', name: 'Iceberg Dark', file: 'Iceberg Dark.yml' },
  { id: 'iceberg-light', name: 'Iceberg Light', file: 'Iceberg Light.yml' },
];
