import { manifest } from '../../../shared/manifest';

export const pebbleAtlasManifest = manifest({
  id: "pebble-atlas",
  title: "Pebble Atlas",
  category: "Ambient",
  description: "Large mineral-colored cells redistribute space between narrow, softly edged channels.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.18, max: 0.4 },
    },
    { name: "cellScale", type: "float", default: 2.5, min: 1.2, max: 4, step: 0.01,
      label: "Cell scale",
      description: "Number of cells across the shorter screen dimension.",
      group: "Shape",
      random: { min: 1.8, max: 3 },
    },
    { name: "gap", type: "float", default: 0.05, min: 0.02, max: 0.14, step: 0.01,
      label: "Channels",
      description: "Width of the channels separating adjacent cells.",
      group: "Shape",
      random: { min: 0.03, max: 0.07 },
    },
    { name: "softness", type: "float", default: 0.02, min: 0.01, max: 0.1, step: 0.01,
      label: "Edge softness",
      description: "Softness of the cell boundaries.",
      group: "Shape",
      random: { min: 0.01, max: 0.04 },
    },
    { name: "wander", type: "float", default: 0.75, min: 0, max: 1, step: 0.01,
      label: "Wander",
      description: "Distance the cell centers travel around their resting positions.",
      group: "Motion",
      random: { min: 0.4, max: 0.85 },
    },
    { name: "color1", type: "color", default: "#9eafa4",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#b6a697",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#8e9fb4",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#ded7c9",
      label: "Background",
      description: "Base color behind the shapes and between their edges.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: { min: 0.7, max: 1.1 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      random: { min: 0.7, max: 1.15 },
      advanced: true,
    },
  ],
});
