import { manifest } from '../../../shared/manifest';

export const gradientLoomManifest = manifest({
  id: "gradient-loom",
  title: "Gradient Loom",
  category: "Geometric",
  description: "Wide translucent strips slide across one another, weaving softly blended patches of color.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      advanced: false,
      random: {"min":0.18,"max":0.4},
    },
    { name: "width", type: "float", default: 0.15, min: 0.06, max: 0.28, step: 0.01,
      label: "Strip width",
      description: "Width of each translucent strip.",
      group: "Shape",
      advanced: false,
      random: {"min":0.11,"max":0.2},
    },
    { name: "softness", type: "float", default: 0.012, min: 0.002, max: 0.08, step: 0.002,
      label: "Edge softness",
      description: "Softness of the strip edges.",
      group: "Shape",
      advanced: false,
      random: {"min":0.012,"max":0.032},
    },
    { name: "travel", type: "float", default: 0.7, min: 0, max: 1.5, step: 0.01,
      label: "Travel",
      description: "Amount of slow sliding and width variation.",
      group: "Motion",
      advanced: false,
      random: {"min":0.4,"max":1},
    },
    { name: "opacity", type: "float", default: 0.7, min: 0.2, max: 1, step: 0.01,
      label: "Pigment",
      description: "Strength of color in each strip and intersection.",
      group: "Color",
      advanced: false,
      random: {"min":0.55,"max":0.85},
    },
    { name: "color1", type: "color", default: "#dba69d",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#a8abd0",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#8db8ac",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#efe5d3",
      label: "Background",
      description: "Color of the space around the composition.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: {"min":0.7,"max":1.1},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min":0.7,"max":1.15},
    },
  ],
});
