import { manifest } from '../../../shared/manifest';

export const prismMosaicManifest = manifest({
  id: "prism-mosaic",
  title: "Prism Mosaic",
  category: "Abstract",
  description: "Drifting glass facets catch colored light along their beveled edges.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "cellScale", type: "float", default: 5, min: 2, max: 10, step: 0.01,
      label: "Cell density",
      description: "Number of glass cells per screen height.",
      group: "Shape",
      random: {"min": 3.8, "max": 6.2},
    },
    { name: "edgeGlow", type: "float", default: 0.65, min: 0, max: 1.5, step: 0.01,
      label: "Edge glow",
      description: "Light caught along the facet boundaries.",
      group: "Color",
      random: {"min": 0.43, "max": 0.88},
    },
    { name: "distortion", type: "float", default: 0.6, min: 0, max: 1, step: 0.01,
      label: "Distortion",
      description: "Amount each facet drifts and changes shape.",
      group: "Motion",
      random: {"min": 0.45, "max": 0.75},
    },
    { name: "bevel", type: "float", default: 0.12, min: 0.02, max: 0.3, step: 0.01,
      label: "Bevel width",
      description: "Width of the angled glass edges.",
      group: "Shape",
      random: {"min": 0.08, "max": 0.16},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#72d4d2",
      label: "Primary color",
      description: "Primary color of the effect.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#bd81d5",
      label: "Secondary color",
      description: "Secondary color of the effect.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#101b2e",
      label: "Background",
      description: "Base color behind the effect.",
      group: "Color",
      random: false,
    },
  ],
});
