import { manifest } from '../../../shared/manifest';

export const paperLanternsManifest = manifest({
  id: "paper-lanterns",
  title: "Paper Lanterns",
  category: "Ambient",
  description: "Warm translucent lanterns float upward through a deep, quiet night.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: {"min": 0.1, "max": 0.6},
    },
    { name: "lanternCount", type: "int", default: 12, min: 4, max: 20, step: 1,
      label: "Lantern count",
      description: "Number of lanterns floating at different depths.",
      group: "Shape",
      random: {"min": 9.6, "max": 14.4},
    },
    { name: "sway", type: "float", default: 0.6, min: 0, max: 1.5, step: 0.01,
      label: "Sway",
      description: "Amount of gentle sideways drift.",
      group: "Motion",
      random: {"min": 0.38, "max": 0.82},
    },
    { name: "translucency", type: "float", default: 0.65, min: 0.1, max: 1, step: 0.01,
      label: "Translucency",
      description: "Warm light passing through the paper.",
      group: "Color",
      random: {"min": 0.52, "max": 0.79},
    },
    { name: "size", type: "float", default: 1, min: 0.5, max: 1.8, step: 0.01,
      label: "Lantern size",
      description: "Overall size of the paper lanterns.",
      group: "Shape",
      random: {"min": 0.8, "max": 1.2},
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      advanced: true,
      random: {"min": 0.7, "max": 1.3},
    },
    { name: "color1", type: "color", default: "#ffb85f",
      label: "Primary color",
      description: "Primary color of the effect.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#ec6b53",
      label: "Secondary color",
      description: "Secondary color of the effect.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#101329",
      label: "Background",
      description: "Base color behind the effect.",
      group: "Color",
      random: false,
    },
  ],
});
