import { manifest } from '../../../shared/manifest';

export const paperFansManifest = manifest({
  id: "paper-fans",
  title: "Paper Fans",
  category: "Geometric",
  description: "Broad fans of terracotta, peach, and aubergine slowly open and overlap.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.3, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.18, max: 0.4 },
    },
    { name: "fanCount", type: "int", default: 2, min: 1, max: 3, step: 1,
      label: "Fans",
      description: "Number of overlapping paper fans.",
      group: "Shape",
      random: { min: 1, max: 3 },
    },
    { name: "radius", type: "float", default: 0.65, min: 0.35, max: 0.95, step: 0.01,
      label: "Radius",
      description: "Length of each fan from its pivot.",
      group: "Shape",
      random: { min: 0.5, max: 0.8 },
    },
    { name: "opening", type: "float", default: 2.2, min: 1.2, max: 3, step: 0.01,
      label: "Opening",
      description: "Angular spread of each fan in radians.",
      group: "Shape",
      random: { min: 1.8, max: 2.6 },
    },
    { name: "flutter", type: "float", default: 0.7, min: 0, max: 1.4, step: 0.01,
      label: "Unfolding",
      description: "Amount of slow opening and turning.",
      group: "Motion",
      random: { min: 0.4, max: 0.9 },
    },
    { name: "color1", type: "color", default: "#c68e79",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#e4b49b",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#78627e",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "background", type: "color", default: "#e5d9c8",
      label: "Background",
      description: "Base color behind the shapes and between their edges.",
      group: "Color",
      random: false,
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      random: { min: 0.7, max: 1.1 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale.",
      group: "Color",
      random: { min: 0.7, max: 1.15 },
      advanced: true,
    },
  ],
});
