import { manifest } from '../../../shared/manifest';

export const meshGradientManifest = manifest({
  id: "mesh-gradient",
  title: "Mesh Gradient",
  description: "Four floating pools of color blend into a soft, shifting mesh.",
  fragment: "shader.glsl",
  uniforms: [
    { name: "speed", type: "float", default: 0.35, min: 0, max: 2, step: 0.01,
      label: "Speed",
      description: "Overall animation speed; zero freezes all movement.",
      group: "Motion",
      random: { min: 0.1, max: 0.65 },
    },
    { name: "blend", type: "float", default: 0.5, min: 0.1, max: 1, step: 0.01,
      label: "Blend",
      description: "How broadly the color pools blend together.",
      group: "Shape",
      random: { min: 0.32, max: 0.68 },
    },
    { name: "warp", type: "float", default: 0.45, min: 0, max: 1, step: 0.01,
      label: "Warp",
      description: "Strength of the flowing distortion.",
      group: "Shape",
      random: { min: 0.25, max: 0.65 },
    },
    { name: "color1", type: "color", default: "#7051ef",
      label: "Color 1",
      description: "Choose palette color 1.",
      group: "Color",
    },
    { name: "color2", type: "color", default: "#ff8bb3",
      label: "Color 2",
      description: "Choose palette color 2.",
      group: "Color",
    },
    { name: "color3", type: "color", default: "#45dfcf",
      label: "Color 3",
      description: "Choose palette color 3.",
      group: "Color",
    },
    { name: "color4", type: "color", default: "#ffc480",
      label: "Color 4",
      description: "Choose palette color 4.",
      group: "Color",
    },
    { name: "brightness", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Brightness",
      description: "Overall light intensity.",
      group: "Color",
      advanced: false,
      random: { min: 0.6, max: 1.2 },
    },
    { name: "saturation", type: "float", default: 1, min: 0, max: 2, step: 0.01,
      label: "Saturation",
      description: "Color intensity; zero is grayscale and one is the original palette.",
      group: "Color",
      advanced: true,
      random: { min: 0.6, max: 1.3 },
    },
    { name: "movementRange", type: "float", default: 0.18, min: 0, max: 0.4, step: 0.01,
      label: "Movement range",
      description: "Distance traveled by each color pool.",
      group: "Motion",
      advanced: true,
      random: { min: 0.1, max: 0.26 },
    },
    { name: "spreadX", type: "float", default: 1, min: 0.5, max: 2, step: 0.01,
      label: "Horizontal spread",
      description: "Horizontal spacing of the color pools.",
      group: "Shape",
      advanced: true,
      random: { min: 0.7, max: 1.3 },
    },
    { name: "spreadY", type: "float", default: 1, min: 0.5, max: 2, step: 0.01,
      label: "Vertical spread",
      description: "Vertical spacing of the color pools.",
      group: "Shape",
      advanced: true,
      random: { min: 0.7, max: 1.3 },
    },
    { name: "warpFrequency", type: "float", default: 1, min: 0.2, max: 3, step: 0.01,
      label: "Warp frequency",
      description: "Number of ripples distorting the mesh.",
      group: "Shape",
      advanced: true,
      random: { min: 0.44, max: 1.56 },
    },
    { name: "influence1", type: "float", default: 1, min: 0.1, max: 3, step: 0.01,
      label: "Color 1 influence",
      description: "Relative area occupied by color 1.",
      group: "Color",
      advanced: true,
      random: { min: 0.42, max: 1.58 },
    },
    { name: "influence2", type: "float", default: 1, min: 0.1, max: 3, step: 0.01,
      label: "Color 2 influence",
      description: "Relative area occupied by color 2.",
      group: "Color",
      advanced: true,
      random: { min: 0.42, max: 1.58 },
    },
    { name: "influence3", type: "float", default: 1, min: 0.1, max: 3, step: 0.01,
      label: "Color 3 influence",
      description: "Relative area occupied by color 3.",
      group: "Color",
      advanced: true,
      random: { min: 0.42, max: 1.58 },
    },
    { name: "influence4", type: "float", default: 1, min: 0.1, max: 3, step: 0.01,
      label: "Color 4 influence",
      description: "Relative area occupied by color 4.",
      group: "Color",
      advanced: true,
      random: { min: 0.42, max: 1.58 },
    },
  ],
});
