// Generated by scripts/generate-shader-registry.mjs. Do not edit by hand.
import { auroraVeilManifest } from './aurora-veil/manifest';
import shader0 from './aurora-veil/shader.glsl';
import { contourDunesManifest } from './contour-dunes/manifest';
import shader1 from './contour-dunes/shader.glsl';
import { emberDriftManifest } from './ember-drift/manifest';
import shader2 from './ember-drift/shader.glsl';
import { flowFieldManifest } from './flow-field/manifest';
import shader3 from './flow-field/shader.glsl';
import { gradientBlobsManifest } from './gradient-blobs/manifest';
import shader4 from './gradient-blobs/shader.glsl';
import { gradientDriftManifest } from './gradient-drift/manifest';
import shader5 from './gradient-drift/shader.glsl';
import { guillocheManifest } from './guilloche/manifest';
import shader6 from './guilloche/shader.glsl';
import { inkBloomManifest } from './ink-bloom/manifest';
import shader7 from './ink-bloom/shader.glsl';
import { interferenceManifest } from './interference/manifest';
import shader8 from './interference/shader.glsl';
import { kineticTilesManifest } from './kinetic-tiles/manifest';
import shader9 from './kinetic-tiles/shader.glsl';
import { liquidChromeManifest } from './liquid-chrome/manifest';
import shader10 from './liquid-chrome/shader.glsl';
import { magneticFilamentsManifest } from './magnetic-filaments/manifest';
import shader11 from './magnetic-filaments/shader.glsl';
import { meshGradientManifest } from './mesh-gradient/manifest';
import shader12 from './mesh-gradient/shader.glsl';
import { opalFilmManifest } from './opal-film/manifest';
import shader13 from './opal-film/shader.glsl';
import { paperLanternsManifest } from './paper-lanterns/manifest';
import shader14 from './paper-lanterns/shader.glsl';
import { phosphorGardenManifest } from './phosphor-garden/manifest';
import shader15 from './phosphor-garden/shader.glsl';
import { plasmaManifest } from './plasma/manifest';
import shader16 from './plasma/shader.glsl';
import { prismMosaicManifest } from './prism-mosaic/manifest';
import shader17 from './prism-mosaic/shader.glsl';
import { rainGlassManifest } from './rain-glass/manifest';
import shader18 from './rain-glass/shader.glsl';
import { audioRibbonsManifest } from './reactive-audio-ribbons/manifest';
import shader19 from './reactive-audio-ribbons/shader.glsl';
import { bassBloomManifest } from './reactive-bass-bloom/manifest';
import shader20 from './reactive-bass-bloom/shader.glsl';
import { pulseRingsManifest } from './reactive-pulse-rings/manifest';
import shader21 from './reactive-pulse-rings/shader.glsl';
import { silkRibbonsManifest } from './silk-ribbons/manifest';
import shader22 from './silk-ribbons/shader.glsl';
import { starDriftManifest } from './star-drift/manifest';
import shader23 from './star-drift/shader.glsl';
import { tidalCausticsManifest } from './tidal-caustics/manifest';
import shader24 from './tidal-caustics/shader.glsl';

export const shaderRegistry: Record<string, import('../core/runtime').ShaderDefinition> = {
  [auroraVeilManifest.id]: { manifest: auroraVeilManifest, source: shader0, animationTime: 'integrated' },
  [contourDunesManifest.id]: { manifest: contourDunesManifest, source: shader1, animationTime: 'integrated' },
  [emberDriftManifest.id]: { manifest: emberDriftManifest, source: shader2, animationTime: 'integrated' },
  [flowFieldManifest.id]: { manifest: flowFieldManifest, source: shader3, animationTime: 'integrated' },
  [gradientBlobsManifest.id]: { manifest: gradientBlobsManifest, source: shader4, animationTime: 'integrated' },
  [gradientDriftManifest.id]: { manifest: gradientDriftManifest, source: shader5, animationTime: 'integrated' },
  [guillocheManifest.id]: { manifest: guillocheManifest, source: shader6, animationTime: 'integrated' },
  [inkBloomManifest.id]: { manifest: inkBloomManifest, source: shader7, animationTime: 'integrated' },
  [interferenceManifest.id]: { manifest: interferenceManifest, source: shader8, animationTime: 'integrated' },
  [kineticTilesManifest.id]: { manifest: kineticTilesManifest, source: shader9, animationTime: 'integrated' },
  [liquidChromeManifest.id]: { manifest: liquidChromeManifest, source: shader10, animationTime: 'integrated' },
  [magneticFilamentsManifest.id]: { manifest: magneticFilamentsManifest, source: shader11, animationTime: 'integrated' },
  [meshGradientManifest.id]: { manifest: meshGradientManifest, source: shader12, animationTime: 'integrated' },
  [opalFilmManifest.id]: { manifest: opalFilmManifest, source: shader13, animationTime: 'integrated' },
  [paperLanternsManifest.id]: { manifest: paperLanternsManifest, source: shader14, animationTime: 'integrated' },
  [phosphorGardenManifest.id]: { manifest: phosphorGardenManifest, source: shader15, animationTime: 'integrated' },
  [plasmaManifest.id]: { manifest: plasmaManifest, source: shader16, animationTime: 'integrated' },
  [prismMosaicManifest.id]: { manifest: prismMosaicManifest, source: shader17, animationTime: 'integrated' },
  [rainGlassManifest.id]: { manifest: rainGlassManifest, source: shader18, animationTime: 'integrated' },
  [audioRibbonsManifest.id]: { manifest: audioRibbonsManifest, source: shader19, animationTime: 'integrated' },
  [bassBloomManifest.id]: { manifest: bassBloomManifest, source: shader20, animationTime: 'integrated' },
  [pulseRingsManifest.id]: { manifest: pulseRingsManifest, source: shader21, animationTime: 'integrated' },
  [silkRibbonsManifest.id]: { manifest: silkRibbonsManifest, source: shader22, animationTime: 'integrated' },
  [starDriftManifest.id]: { manifest: starDriftManifest, source: shader23, animationTime: 'integrated' },
  [tidalCausticsManifest.id]: { manifest: tidalCausticsManifest, source: shader24, animationTime: 'integrated' },
};
export const shaderIds = Object.keys(shaderRegistry);
